language: node_js
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - bc
node_js:
  - v4.0.0
  - lts/argon
  - lts/boron
  - stable
script:
  - make test-travis
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
